### ISSUE TITLE
Does anyone have GeoFire performance "unit test" (for Java) tests?

### ISSUE THREAD

**Issue by ErstwhileWork** [firebase/geofire#10]
I have some probably performance improvements for some of the GeoFire methods, but I would like to use a performance test (suite?) that the GeoFire folks have used before submitting any pull request.

Where might I find such?

If there are none, are there any other set of tests that folks have wanted to have for GeoFire that I should consider if I write the performance tests myself?

**Comment by jwngr** [comment]
We don't have a performance test suite nor do we track performance from one release to the next. If you have some performance improvements, feel free to put together a performance test suite and provide some before and after numbers. A performance suite built by the maintainers is not planned though.
