### ISSUE TITLE
Firebase/Firebase.h file not found

### ISSUE THREAD

**Issue by a9austin** [firebase/geofire#4]
#3 I ran a pod update today and ran into this error 

> 'Firebase/Firebase.h' file not found

This is currently the line of code I have in my pod file `pod 'GeoFire', '>= 1.1'`
I have the Firebase pod also `pod 'Firebase', '~> 2.3.1'`

**GeoFire.m**

#import "GeoFire.h"
#import "GeoFire+Private.h"
#import "GFGeoHash.h"
#import "GFQuery+Private.h"
#import < Firebase/Firebase.h > // Error Here

![screen shot 2016-03-15 at 4 37 56 pm](https://cloud.githubusercontent.com/assets/5395918/13797590/f5f719d8-eacb-11e5-8440-614dabfb578b.png)

**Comment by jwngr** [comment]
Please try again with the latest version of the Firebase and GeoFire and, if you are still having issues, open up a new issue on the [GeoFire for iOS repo](https://github.com/firebase/geofire-objc/issues/).

Also, check out https://github.com/firebase/geofire-objc/issues/48 and https://github.com/firebase/geofire-objc/issues/51 in case those will help you track down how to properly install GeoFire on iOS.
