### ISSUE TITLE
Rules

### ISSUE THREAD

**Issue by AlphaNerds** [firebase/geofire#7]
I'm quite new to Firebase, but I'm trying to replicate what you've done at sflivebus.com, but with a different dataset. So far i can't quite get it working...

I've recreated my own db on firebase (https://firemap-1f7d5.firebaseio.com/) and replicated your data, just to make it easier to get everything working. Basically want to get your example running on my server, and then start working on switching data sets and working from there.

I can get the map partially working, but my data is not coming in. [See example here](http://dev.alphanerdsmedia.com/GoodBetterMap)

Maybe my rules are wrong?

{
  "rules": {
    "_geofire": {
      // Allow anyone to read the GeoFire index
      ".read": true,

      // Index each location's geohash for faster querying
      ".indexOn": ["g"],

      // Schema validation
      "$key": {
        // Allow anyone to add, update, or remove keys in the GeoFire index
        ".write": true,

        // Key validation
        ".validate": "newData.hasChildren(['g', 'l']) && newData.getPriority().length <= 22 && newData.getPriority().length > 0",

        // Geohash validation
        "g": {
          ".validate": "newData.val() == newData.parent().getPriority()"
        },

        // Location coordinates validation
        "l": {
          "0" : {
            ".validate": "newData.isNumber() && newData.val() >= -90 && newData.val() <= 90"
          },
          "1" : {
            ".validate": "newData.isNumber() && newData.val() >= -180 && newData.val() <= 180"
          },
          "$other": {
            ".validate": false
          }
        },

        // Don't allow any other keys to be written
        "$other": {
          ".validate": false
        }
      }
    }
  }
}

The modded sfVehicle.js file looks like this:
```
var map;
// Set the center as Firebase HQ
var locations = {
  "FirebaseHQ": [37.785326, -122.405696],
  "Caltrain": [37.7789, -122.3917],
  "Home": [46.0813169, -64.9958045]
};
var center = locations["Home"];
// Query radius
var radiusInKm = 0.5;
// Get a reference to the Firebase public transit open data set
**var transitFirebaseRef = new Firebase("https://firemap-1f7d5.firebaseio.com/")**
// Create a new GeoFire instance, pulling data from the public transit data
**var geoFire = new GeoFire(transitFirebaseRef);**
// am I suppose to use this one?  var geoFire = new GeoFire(transitFirebaseRef.child("_geofire"));
```

and my data set looks like this in Firebase:
```
firemap-1f7d5
      _geofire
           routes
                3
                    5502: true
                    5508: true
                    5510: true
                7
                    6402:true
                    6403:true
                    6404:true
          vehicles
               6
                    dirTag: "59___O_F00"
                    heading: 353
                    id: 6
                    lat: 46.0713169
                    lon: -64.7958045
                    predictable: true
                    routeTag: "59"
                    secsSinceReport: 4
                    speedKmHr: 0
                    timstamp: 1459450322184
                    vtype: "bus"
              7
                    dirTag: "59___O_F00"
                    heading: 353
                    id: 6
                    lat: 46.0713169
                    lon: -64.7958045
                    predictable: true
                    routeTag: "59"
                    secsSinceReport: 4
                    speedKmHr: 0
                    timstamp: 1459450322184
                    vtype: "bus"
             ....
       ....
....
```

**Comment by jwngr** [comment]
We are going to need a more minimal repro to help you debug. Offhand, the most likely explanation is that your GeoFire does not contain any points which match your GeoQuery. I'd suggest making your GeoQuery very large (1000s of kilometers) and seeing if any items match at that point. It's possible that your script which populates the GeoFire index just does not work properly, but I can't tell without seeing a more minimal repro than an entire app.
