### ISSUE TITLE
Get results by passing lat and long

### ISSUE THREAD

**Issue by bmanderscheid** [firebase/geofire#8]
In your example description, you could pass a place id and get back ids of places nearby that place you passed in.  The firebase app we are planning wants to get back the same results, but by passing lat and long, not a specific place id.  Can this be accomplished with geofire?

**Comment by netdawgx** [comment]
I am fairly sure the example description, although it's not explicitly stated, is passing location data (and not place ID) to return a list of nearby place IDs.

So yes I believe it is not only possible but was built for precisely your use case. :)

**Comment by bmanderscheid** [comment]
But a list of records from MY data in firebase, correct?  Assuming my records had place ids, and/or lat and long fields.

**Comment by netdawgx** [comment]
Yes - so using the example in the readme:

Bars
    Bar ID 1
        Bar Name
        Bar Address
        Bar Phone
        Bar Rating
    Bar ID 2
        Bar Name
        Bar Address
        Bar Phone
        Bar Rating

GeoFire
    56,78 -> Bar 1
    78,42 -> Bar 2

GeoFire will use your coordinates (current location or inputted location) to query the database and find out which bars are closest to you and return a list of the closest Bar IDs. You can then take the list of Bar IDs to pull data from the other part of your database that has Name, Address, etc. and display however you want. :)

**Comment by bmanderscheid** [comment]
Brilliant!!
